### ISSUE TITLE
MIT license is incompatible with LGPLv2 when linked statically

### ISSUE THREAD

**Issue by moncruist** [a1ien/libusb1-sys#14]
libusb has LGPLv2 license which only allows to be used with MIT or proprietary license when linked dynamically. If you link your crate statically, it's considered as derivative work and cannot be licensed under MIT license, only LGPLv2 or GPL. And then the same applies for every other crate which has dependency on this one.

**Comment by a1ien** [comment]
Which option do you think is more correct?
1) Remove the ability to statically link.
2) Specify that if you link statically then you apply a license from libusb

**Comment by moncruist** [comment]
As for me the second option is better. In addition to that, I think dynamic linking should be turned on by default, making it safe to use for those who don't read manuals.
