### ISSUE TITLE
build.rs does not support cross-compiling to different env

### ISSUE THREAD

**Issue by tanriol** [a1ien/libusb1-sys#18]
I've tried cross-compiling from Linux to `x86_64-pc-windows-gnu` and failed with `poll.h: No such file or directory`.

This is caused by environment confusion in the build script. The build script extensively uses `#[cfg(...)]` and `cfg!(...)` to determine the target environment and adjust the compilation process. However, in case of cross-compilation the build script `cfg` environment reflects the host system – the one the build script itself is compiled for – not the target system. For the target system one should use the [environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

**Comment by a1ien** [comment]
As work around I suggest cross-compile native libusb. And use pkg-config as suggest in readme. It's must work for cross-compile for windows

**Comment by avantgardnerio** [comment]
I just saw this issue. I had the same problem. See this PR for a fix https://github.com/a1ien/libusb1-sys/pull/23
