### ISSUE TITLE
libusb_fill_bulk_transfer 

### ISSUE THREAD

**Issue by flukejones** [a1ien/libusb1-sys#19]
I see `libusb_fill_bulk_transfer` isn't wrapped here. I'm wondering if we can add it and associated other functions if also missing.

Being able to use `libusb_fill_bulk_transfer`  and `libusb_submit_transfer` + `libusb_alloc_transfer` upstream in `rusb` would make things a lot easier to manage better throughput in transfers.

I found this [doc](https://elinux.org/images/a/ae/Ott--usb_and_the_real_world.pdf) provided some good explanations in a concise way.

**Comment by a1ien** [comment]
libusb_fill_bulk_transfer is just wrapper that set field you can implement it manual it best way
https://github.com/libusb/libusb/blob/da87201f7a5580db16565b1ecc7eefe0fcb5bb59/libusb/libusb.h#L1587

**Comment by ianrrees** [comment]
+1 for the `libusb_fill_*()` methods.  I understand that they're not difficult to duplicate, but it is surprising they're not available in libusb1-sys despite being part of the libusb API.
