### ISSUE TITLE
Bus Factor

### ISSUE THREAD

**Issue by anton-dutov** [a1ien/libusb1-sys#3]
Your project is fork of libusb-sys crate, which was abandoned, may be some time later you lose motivation or some other reasons (Bus Factor) for abandon support this crate
Many peoples interested in rust usb support, to avoid busfactor i propose two choises:
- please join to [rustbus initiative](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046)  
- or join to my [hal-rs initiative](https://github.com/hal-rs/initiative/blob/master/README.md) as member to track and keep up to date hardware related crates, i annoce my initiative on reddit litle bit later to involve developers

**Comment by a1ien** [comment]
Done
